[build]
  command = "npm run netlify-build && npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  CI = "false"
  SKIP_TYPESCRIPT_CHECK = "1"
  NEXT_DISABLE_ESLINT = "1"
  TYPESCRIPT_IGNORE_ERRORS = "1"
  # Mock API keys for build time
  OPENAI_API_KEY = "sk-netlify-build-mock-key"
  DEEPSEEK_API_KEY = "sk-netlify-build-mock-key"
  USE_MOCK_SERVICES = "true"
  VERCEL_BUILD_MODE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]
  included_files = ["app/lib/build-bypass/**", "app/lib/**", "node_modules/**"]
  timeout = 30  # Increase timeout to 30 seconds

# Handle redirects for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Special redirect for API routes (ensure API endpoints work)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Environment variable configuration for different contexts
[context.production.environment]
  CI = "false"
  SKIP_TYPESCRIPT_CHECK = "1"
  NEXT_DISABLE_ESLINT = "1"
  TYPESCRIPT_IGNORE_ERRORS = "1"
  NEXT_PUBLIC_APP_ENV = "production"
  NEXT_PUBLIC_APP_NAME = "EMC Electronic Music Content Generator"
  
[context.deploy-preview.environment]
  CI = "false"
  SKIP_TYPESCRIPT_CHECK = "1"
  NEXT_DISABLE_ESLINT = "1"
  TYPESCRIPT_IGNORE_ERRORS = "1"
  # Mock API keys for preview builds
  OPENAI_API_KEY = "sk-netlify-build-mock-key"
  DEEPSEEK_API_KEY = "sk-netlify-build-mock-key"
  USE_MOCK_SERVICES = "true"
  NEXT_PUBLIC_APP_ENV = "preview"
  NEXT_PUBLIC_APP_NAME = "EMC Electronic Music Content Generator (Preview)"
