[build]
  command = "npm run netlify-build && npm run build"
  publish = ".next"
  functions = "netlify/functions"  # Directory with serverless functions

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  SKIP_TYPESCRIPT_CHECK = "1"
  NEXT_DISABLE_ESLINT = "1"
  TYPESCRIPT_IGNORE_ERRORS = "1"
  # Mock API keys for build time only
  MOCK_OPENAI_API_KEY = "sk-netlify-build-mock-key"
  MOCK_DEEPSEEK_API_KEY = "sk-netlify-build-mock-key"
  # Force mock services during build
  USE_MOCK_SERVICES = "true"
  VERCEL_BUILD_MODE = "true"
  NODE_VERSION = "18"

# Handle CORS properly
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"

# Handle API routes - force them to our serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
